eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  config: classpath:logback.xml
spring:
  application:
    name: zuul